#!/usr/bin/env python3
"""gen_released_directive_hashes.py — 역대 발행 지침 해시 표 생성기 (v116-ceo-directive-hold).

무엇: `cysjavis-pack/directives/{CEO_TEMPLATE,MASTER_DIRECTIVE}.md` 가 제품에 실려 나간 **모든 판의
바이트 sha256** 을 모아 `src/released_directive_hashes.rs` 에 상수 표로 쓴다.
설치기(src/pack.rs)는 이 표로 「디스크 사본이 제품이 쓴 그 바이트 그대로인가」를 판정한다 —
  · CEO_TEMPLATE 표: 승격 사본(MASTER_DIRECTIVE.md = CEO_TEMPLATE 바이트 사본)이 옛 판이어도 알아본다
    (옛 사이드카가 manifest[CEO] 를 먼저 전진시킨 기계 = 1085 VM-B 형상 구제 · ⓑ⁺).
  · MASTER_DIRECTIVE 표: 강등으로 옛 표준 판이 된 사본·낡은 .pre-ceo 를 「손대지 않은 옛 발행본」으로
    알아본다(ⓔ · 1098 형상).
출처 = git 태그 `v0.14.*` · `v1.*`(발행 태그) + **현재 작업 트리**(다음에 발행될 판). 현재 판을 넣지
않으면 이 판이 발행된 뒤 다음 판의 설치기가 이 판을 못 알아본다 — `--check` 와 cargo 시험
(`released_tables_cover_current_embed`)이 이 누락을 적색으로 잡는다.

사용: python3 scripts/gen_released_directive_hashes.py          # 생성(덮어쓰기)
      python3 scripts/gen_released_directive_hashes.py --check  # 표류 검사(exit 1 = 재생성 필요)
"""
import hashlib
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "released_directive_hashes.rs")
FILES = {
    "RELEASED_CEO_TEMPLATE_SHA256": "cysjavis-pack/directives/CEO_TEMPLATE.md",
    "RELEASED_MASTER_DIRECTIVE_SHA256": "cysjavis-pack/directives/MASTER_DIRECTIVE.md",
}
TAG_PATTERNS = ("v0.14.*", "v1.*")


def git(*args):
    return subprocess.run(["git", "-C", ROOT] + list(args), capture_output=True, check=False)


def tags():
    out = set()
    for pat in TAG_PATTERNS:
        r = git("tag", "-l", pat)
        out.update(t for t in r.stdout.decode().split() if t)
    return sorted(out)


def collect(rel):
    hashes = set()
    for t in tags():
        r = git("show", "%s:%s" % (t, rel))
        if r.returncode == 0 and r.stdout:
            hashes.add(hashlib.sha256(r.stdout).hexdigest())
    with open(os.path.join(ROOT, rel), "rb") as f:
        hashes.add(hashlib.sha256(f.read()).hexdigest())
    return sorted(hashes)


def render():
    lines = [
        "// @generated by scripts/gen_released_directive_hashes.py — 손으로 고치지 마라.",
        "// 역대 발행 지침 바이트 sha256(git 태그 v0.14.* · v1.* + 생성 시점 작업 트리).",
        "// 지침 원문을 고치면 `python3 scripts/gen_released_directive_hashes.py` 로 재생성한다",
        "// (안 하면 cargo 시험 released_tables_cover_current_embed 와 --check 가 적색).",
        "",
    ]
    for const, rel in FILES.items():
        hs = collect(rel)
        lines.append("pub(crate) const %s: &[&str] = &[" % const)
        lines.extend('    "%s",' % h for h in hs)
        lines.append("];")
        lines.append("")
    return "\n".join(lines)


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != text:
            sys.stderr.write("[gen_released_directive_hashes] 표류 — %s 재생성 필요\n" % OUT)
            return 1
        print("[gen_released_directive_hashes] OK")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("[gen_released_directive_hashes] wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
